{{- if .Values.operator.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-operator
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
rules:
- apiGroups:
  - proxy.livellm.ai
  resources:
  - llmproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.livellm.ai
  resources:
  - llmproviders/finalizers
  verbs:
  - update
- apiGroups:
  - proxy.livellm.ai
  resources:
  - llmproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-operator
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "chart.fullname" . }}-operator
subjects:
- kind: ServiceAccount
  name: {{ include "chart.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
{{- end }}
