{{- if .Values.operator.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.fullname" . }}-operator
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
{{- end }}
