{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-env
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.env.encryption_salt }}
  ENCRYPTION_SALT: {{ .Values.env.encryption_salt | quote }}
  {{- end }}
  {{- if .Values.env.redis_url }}
  REDIS_URL: {{ .Values.env.redis_url | quote }}
  {{- else if .Values.redis.enabled }}
  REDIS_URL: "redis://{{ include "chart.fullname" . }}-redis:6379/0"
  {{- end }}
  {{- if .Values.env.token_count_overhead }}
  TOKEN_COUNT_OVERHEAD: {{ .Values.env.token_count_overhead | quote }}
  {{- end }}
{{- end }}
