{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-env
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.env.logfire_write_token }}
  LOGFIRE_WRITE_TOKEN: {{ .Values.env.logfire_write_token | quote }}
  {{- end }}
  {{- if .Values.env.otel_exporter_otlp_endpoint }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.env.otel_exporter_otlp_endpoint | quote }}
  {{- end }}
  {{- if .Values.env.encryption_salt }}
  ENCRYPTION_SALT: {{ .Values.env.encryption_salt | quote }}
  {{- end }}
  {{- if .Values.env.redis_url }}
  REDIS_URL: {{ .Values.env.redis_url | quote }}
  {{- end }}
  {{- if .Values.env.token_count_overhead }}
  TOKEN_COUNT_OVERHEAD: {{ .Values.env.token_count_overhead | quote }}
  {{- end }}
  {{- if .Values.env.enable_storage_reconciliation }}
  ENABLE_STORAGE_RECONCILIATION: {{ .Values.env.enable_storage_reconciliation | quote }}
  {{- end }}
  {{- if .Values.env.reconciliation_interval_seconds }}
  RECONCILIATION_INTERVAL_SECONDS: {{ .Values.env.reconciliation_interval_seconds | quote }}
  {{- end }}
{{- end }}
